blank_issues_enabled: true
contact_links:
    - name: Send an e-mail to the developer
      url: mailto:jgracia9988@gmail.com
      about: Please do NOT use this email to post issues or feature requests (only important business/personal contact).
