blank_issues_enabled: true
contact_links:
  - name: Send an e-mail the developer
    url: mailto:FAKE_TEST_EMAIL
    about: Please do NOT use this email to post issues or feature requests (only important business/personal contact).
